//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAlmaMVC.KurServis {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KurServis.IKurService")]
    public interface IKurService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKurService/ParaBirimleriGetir", ReplyAction="http://tempuri.org/IKurService/ParaBirimleriGetirResponse")]
        System.Collections.Generic.List<string> ParaBirimleriGetir();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKurService/ParaBirimleriGetir", ReplyAction="http://tempuri.org/IKurService/ParaBirimleriGetirResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> ParaBirimleriGetirAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKurService/KurlarGetir", ReplyAction="http://tempuri.org/IKurService/KurlarGetirResponse")]
        System.Collections.Generic.List<double> KurlarGetir(string kurTipi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKurService/KurlarGetir", ReplyAction="http://tempuri.org/IKurService/KurlarGetirResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<double>> KurlarGetirAsync(string kurTipi);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKurServiceChannel : ServiceAlmaMVC.KurServis.IKurService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KurServiceClient : System.ServiceModel.ClientBase<ServiceAlmaMVC.KurServis.IKurService>, ServiceAlmaMVC.KurServis.IKurService {
        
        public KurServiceClient() {
        }
        
        public KurServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KurServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KurServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KurServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<string> ParaBirimleriGetir() {
            return base.Channel.ParaBirimleriGetir();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> ParaBirimleriGetirAsync() {
            return base.Channel.ParaBirimleriGetirAsync();
        }
        
        public System.Collections.Generic.List<double> KurlarGetir(string kurTipi) {
            return base.Channel.KurlarGetir(kurTipi);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<double>> KurlarGetirAsync(string kurTipi) {
            return base.Channel.KurlarGetirAsync(kurTipi);
        }
    }
}
